### ISSUE TITLE
Extract the text for optimize access and translation.

### ISSUE THREAD

**Issue by Mandaar** [jaxxa/StarWarsFFG#5]
Hello,
First thank for your amazing work.
But actually it's complicated to translate your module because your text values is not set in variable, all Star wars FFG adjustment is in developpement file directly.
Honestly it's not an optimal way to manage text content, just to make a correction, you have to find and edit in the files directly.

If i watch DnD5 module they set for exemple {{ localize "DND5E.Inventory" }}.
Thank you, Have a good day

**Comment by jaxxa** [comment]
Hey thanks for the idea. 
I am working with Esrin and moving Development over to https://github.com/StarWarsFoundryVTT/StarWarsFFG

It looks like this has already been done in the dev branch over there.
